### ISSUE TITLE
The text on consent screen is not readable with android dark theme

### ISSUE THREAD

**Issue by nazarbratko** [cookie-information/android-release#15]

**Comment by HannaSMatches** [comment]
@nazarbratko Thank you for bringing this up.
Are you able to confirm the following:
-What version are you using?
-Are you using a custom ui?

Thank You

**Comment by HannaSMatches** [comment]
Thank you. WiIl investigate and update surely.
Please note version 1.0.6 has been released, and adding custom UI is possible. This may be a  quick solution.
But don't worry will make sure this issue will be resolved asap.

**Comment by HenrikBacher** [comment]
@HannaSMatches any updates on this issue?

**Comment by HannahShulman** [comment]
Thank you for the pinging.
I will be releasing today a version with the fix. 
I see it hasn't been released with the previous versions. My apologies.
