### ISSUE TITLE
The Privacy popup can be dismissed with a back swipe or tap on device's back button

### ISSUE THREAD

**Issue by andy-3000** [cookie-information/android-release#21]
The privacy screen should not be cancellable, to dismiss it the user needs to save the privacy preferences. Currently it is possible to dismiss the screen with a back swipe or with a tap on the back button.

**Comment by HenrikBacher** [comment]
Any updates on this issue?

**Comment by HannahShulman** [comment]
Confirmed fix on version 2.0.2
