### ISSUE TITLE
Missing 2.0.4 release

### ISSUE THREAD

**Issue by vitoksmile** [cookie-information/android-release#43]
The latest version on [maven is 2.0.2](https://central.sonatype.com/artifact/com.cookieinformation/mobileconsents/versions), however there are [no tags and release notes for 2.0.2](https://github.com/cookie-information/android-release/releases)

**Comment by vitoksmile** [comment]
@HannahShulman any updates here?

**Comment by vitoksmile** [comment]
the same with 2.0.4

**Comment by HannahShulman** [comment]
@vitoksmile My apologies for the late response. A tag has been created with changes. Thanks
