### ISSUE TITLE
Back navigation

### ISSUE THREAD

**Issue by VitaliyShuba** [cookie-information/android-release#44]
Hello. 
Currently, we use version 2.0.1
Everything is ok except the one nuance, sometimes sdk allows back navigation from consent window, sometimes it shows "Please accept consents".
Is there a way to control back navigation? So in some cases we allow it and in some scenarios - not.

**Comment by HannahShulman** [comment]
Good Morning,
Navigating back is allowed just once a user has given their consent/rejected them, therefore you can prob not navigate back.
Is this the situation you are talking about? If not, please provide more information, so we can investigate this. Thanks.

**Comment by VitaliyShuba** [comment]
It is vice versa, first time after fresh app install when we call `displayConsents` - user is allowed to navigate back. But we don't want this behavior.

**Comment by HannahShulman** [comment]
Thanks for your information, I will investigate this.

**Comment by andy-3000** [comment]
Hi @VitaliyShuba, thanks for the report! We're expecting the fix by the end of the week and a release during next week. We'll let you know when it's done.

**Comment by andy-3000** [comment]
@VitaliyShuba we've released v 2.0.3 that fixes the back navigation bug. I'm closing the issue.
