### ISSUE TITLE
MobileConsents.initSdk()

### ISSUE THREAD

**Issue by VitaliyShuba** [cookie-information/android-release#45]
Hello, I saw that you removed `MobileConsents.initSdk()` suspend function.
May I ask why? we use this function, because we use coroutines, we don't need one with "callback".

**Comment by andy-3000** [comment]
Hi @VitaliyShuba! Thank you for your report. We'll get back to you on this as soon as possible.

**Comment by VitaliyShuba** [comment]
Hello @andy-3000, any updates on this topic? Should we wait or should we work with current version?

**Comment by HannahShulman** [comment]
Hello @VitaliyShuba 
Version 2.0.4 has been released with the former initSdk().
Please let us know if we can assist with anything else.
