### ISSUE TITLE
Error: There are no consent items in the database

### ISSUE THREAD

**Issue by StefanSmudja** [cookie-information/android-release#56]
Hi I'm in the process of integrating cookie-information in my code base and I've encountered that showing the popup is not possible to do. 

I call `showPrivacyPopup`, and what I've made out of it is that `cacheLatestConsentSolution` always throws the `IllegalStateException` since the saved user consents are empty. 

So it's technically a catch 22 situation where I can't prompt the consent popup because I don't have any consents stored. 

```
 private suspend fun cacheLatestConsentSolution(callingActivity: ComponentActivity, userId: String?):Result<Unit> {
        return runCatching {
            val sdk = ConsentSDK(
                callingActivity,
                clientID,
                clientSecret,
                solutionId,
                languageCode
            )

            sdk.init().getOrThrow()
            sdk.cacheLatestConsentSolution().getOrThrow()
            val consents = sdk.getLatestSavedUserConsents(userId).getOrThrow()
            if (consents.isEmpty()) {
                throw IllegalStateException("There are no consent items in the database")
            }
        }
    }
```

Kind regards, Stefan :)

**Comment by furkanShape** [comment]
Hi @StefanSmudja did you find out the problem? I am facing the same issue

**Comment by StefanSmudja** [comment]
No worries! @furkanShape 
I'm glad I could help out :)
